grpcport: 50151
httpport: 8082
tlsfiles:
database: redis
dbaddress: 127.0.0.1:6379
buildenv: intel_e2000
tracer: false
subscribers:
 - name: "lvm"
   priority: 2
   events: ["vrf", "bridge-port", "tun-rep"]
 - name: "lgm"
   priority: 1
   events: ["vrf", "svi", "logical-bridge"]
 - name: "frr"
   priority: 3
   events: ["vrf", "svi"]
 - name: "netlink"
   priority: 4
   events: ["tun-rep"]
 - name: "intel_e2000"
   priority: 5
   events: ["vrf", "logical-bridge", "bridge-port", "svi", "sa", "tun-rep"]
grpc:
    server_addresses:
      - 0.0.0.0
    server_port: 51703
    num_threads: 10
    static_external_macs: []
interfaces:
    phyports:
      - rep: "eth1"
        vsi: 0
      - rep: "eth3"
        vsi: 1
    grpcacc: "host"
    grpchost: "00:20:00:00:14:48"
    vrfmux: "eth4"
    portmux: "eth5"
    tunnelmux: "eth6"
p4:
    enabled: true
    config:
        p4infofile: /root/p4files/opi_ln.p4info.txt
        binfile: /root/p4files/opi_ln.pb.bin
linuxfrr:
    enabled: true
    defaultvtep: "vxlan-vtep"
    ipmtu: 1460
    localas: 65001
netlink:
    enabled: true
    pollinterval: 1
    grddefaultroute: false
    enableecmp: true
ipsec:
    enabled: true
    tunnels:
      - name: "pe2-1"
        ifid: 101
        # The IPs below are just examples. Replace them with the real IPs of the system
        ip: "25.25.25.3/32"
        remoteip: "26.26.26.4/32"
      - name: "pe2-2"
        ifid: 102
        ip: "27.27.27.5/32"
        remoteip: "28.28.28.6/32"
loglevel:
    db: INFO
    grpc: INFO
    linux: INFO
    netlink: INFO
    p4: DEBUG
